project:
  type: website
  output-dir: docs

website:
  title: "izo_1026_groups"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd
      - model.qmd
#      - analysis.qmd
      - evaluation.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    
editor: visual

